prometheus:
  nodeExporter:
    hostRootfs: false
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  server:
    ingress:
      enabled: true
      hosts:
        - TF_POPULATED
      path: /
      # path: /prometheus(/|$)(.*)
      annotations:
        kubernetes.io/ingress.class: public
        # nginx.ingress.kubernetes.io/rewrite-target: /$2
        # nginx.ingress.kubernetes.io/use-regex: "true"
